# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'sinatra'
gem 'puma'
gem "sinatra-contrib", "~> 2.2"
gem "rack-flash3", "~> 1.0"
